import { l10n } from 'vscode';

const icons = {
	feedback:                             { name: l10n.t('Feedback'),                       label: '$(feedback)',                                },
	file:                                 { name: l10n.t('File'),                           label: '$(file)',                                    },
	fileAdd:                              { name: l10n.t('File Add'),                       label: '$(file-add)',                                },
	fileBinaly:                           { name: l10n.t('File Binaly'),                    label: '$(file-binary)',                             },
	fileCode:                             { name: l10n.t('File Code'),                      label: '$(file-code)',                               },
	fileDirectory:                        { name: l10n.t('File Directory'),                 label: '$(file-directory)',                          },
	fileDirectoryCreate:                  { name: l10n.t('File Directory Create'),          label: '$(file-directory-create)',                   },
	fileMedia:                            { name: l10n.t('File Media'),                     label: '$(file-media)',                              },
	filePdf:                              { name: l10n.t('File PDF'),                       label: '$(file-pdf)',                                },
	fileSubmodule:                        { name: l10n.t('File Submodule'),                 label: '$(file-submodule)',                          },
	fileSymlinkDirectory:                 { name: l10n.t('File Symlink Directory'),         label: '$(file-symlink-directory)',                  },
	fileSymlinkFile:                      { name: l10n.t('File Symlink File'),              label: '$(file-symlink-file)',                       },
	fileText:                             { name: l10n.t('File Text'),                      label: '$(file-text)',                               },
	fileZip:                              { name: l10n.t('File Zip'),                       label: '$(file-zip)',                                },
	files:                                { name: l10n.t('Files'),                          label: '$(files)',                                   },
  filterFilled:                         { name: l10n.t('Filter Filled'),                  label: '$(filter-filled)',                           },
	filter:                               { name: l10n.t('Filter'),                         label: '$(filter)',                                  },
	flame:                                { name: l10n.t('Flame'),                          label: '$(flame)',                                   },
	fold:                                 { name: l10n.t('Fold'),                           label: '$(fold)',                                    },
	foldDown:                             { name: l10n.t('Fold Down'),                      label: '$(fold-down)',                               },
	foldUp:                               { name: l10n.t('Fold Up'),                        label: '$(fold-up)',                                 },
	folder:                               { name: 'Folder',                                 label: '$(folder)',                                  },
	folderActive:                         { name: l10n.t('Folder Active'),                  label: '$(folder-active)',                           },
  folderLibrary:                        { name: l10n.t('Folder Library'),                 label: '$(folder-library)',                          },
	folderOpened:                         { name: l10n.t('Folder Opened'),                  label: '$(folder-opened)',                           },
  game:                                 { name: l10n.t('Game'),                           label: '$(game)',                                    },
	gather:                               { name: l10n.t('Gather'),                         label: '$(gather)',                                  },
	gear:                                 { name: l10n.t('Gear'),                           label: '$(gear)',                                    },
	gift:                                 { name: l10n.t('Gift'),                           label: '$(gift)',                                    },
  gist:                                 { name: l10n.t('Gist'),                           label: '$(gist)',                                    },
	gistFork:                             { name: l10n.t('Gist Fork'),                      label: '$(gist-fork)',                               },
	gistNew:                              { name: l10n.t('Gist New'),                       label: '$(gist-new)',                                },
	gistPrivate:                          { name: l10n.t('Gist Private'),                   label: '$(gist-private)',                            },
	gistSecret:                           { name: l10n.t('Gist Secret'),                    label: '$(gist-secret)',                             },
	gitBranch:                            { name: l10n.t('Git Branch'),                     label: '$(git-branch)',                              },
	gitBranchCreate:                      { name: l10n.t('Git Branch Create'),              label: '$(git-branch-create)',                       },
	gitBranchDelete:                      { name: l10n.t('Git Branch Delete'),              label: '$(git-branch-delete)',                       },
	gitCommit:                            { name: l10n.t('Git Commit'),                     label: '$(git-commit)',                              },
	gitCompare:                           { name: l10n.t('Git Compare'),                    label: '$(git-compare)',                             },
  gitFetch:                             { name: l10n.t('Git Fetch'),                      label: '$(git-fetch)',                               },
	gitForkPrivate:                       { name: l10n.t('Git Fork Private'),               label: '$(git-fork-private)',                        },
	gitMerge:                             { name: l10n.t('Git Merge'),                      label: '$(git-merge)',                               },
	gitPullRequest:                       { name: l10n.t('Git Pull Request'),               label: '$(git-pull-request)',                        },
	gitPullRequestAbandoned:              { name: l10n.t('Git Pull Request Abandoned'),     label: '$(git-pull-request-abandoned)',              },
  gitPullRequestClosed:                 { name: l10n.t('Git Pull Request Closed'),        label: '$(git-pull-request-closed)',                 },
	gitPullRequestCreate:                 { name: l10n.t('Git Pull Request Create'),        label: '$(git-pull-request-create)',                 },
  gitPullRequestDraft:                  { name: l10n.t('Git Pull Request Draft'),         label: '$(git-pull-request-draft)',                  },
  gitPullRequestNewChanges:             { name: l10n.t('Git Pull Request New Changes'),   label: '$(git-pull-request-new-changes)',            },
  gitPullRequestGoToChanges:            { name: l10n.t('Git Pull Request Go To Changes'), label: '$(git-pull-request-go-to-changes)',          },
	github:                               { name: l10n.t('Github'),                         label: '$(github)',                                  },
	githubAction:                         { name: l10n.t('Github Action'),                  label: '$(github-action)',                           },
	githubAlt:                            { name: l10n.t('Github Alt'),                     label: '$(github-alt)',                              },
	githubInverted:                       { name: l10n.t('Github Inverted'),                label: '$(github-inverted)',                         },
	globe:                                { name: l10n.t('Globe'),                          label: '$(globe)',                                   },
	goToFile:                             { name: l10n.t('Go to File'),                     label: '$(go-to-file)',                              },
	grabber:                              { name: l10n.t('Grabber'),                        label: '$(grabber)',                                 },
	graph:                                { name: l10n.t('Graph'),                          label: '$(graph)',                                   },
	graphLeft:                            { name: l10n.t('Graph Left'),                     label: '$(graph-left)',                              },
  graphLine:                            { name: l10n.t('Graph Line'),                     label: '$(graph-line)',                              },
	gripper:                              { name: l10n.t('Gripper'),                        label: '$(gripper)',                                 },
	groupByRefType:                       { name: l10n.t('Group By Ref Type'),              label: '$(group-by-ref-type)',                       },
	heart:                                { name: l10n.t('Heart'),                          label: '$(heart)',                                   },
	history:                              { name: l10n.t('History'),                        label: '$(history)',                                 },
	home:                                 { name: l10n.t('Home'),                           label: '$(home)',                                    },
	horizontalRule:                       { name: l10n.t('Horizontal Rule'),                label: '$(horizontal-rule)',                         },
	hubot:                                { name: l10n.t('Hubot'),                          label: '$(hubot)',                                   },
	inbox:                                { name: l10n.t('Inbox'),                          label: '$(inbox)',                                   },
  indent:                               { name: l10n.t('Indent'),                         label: '$(indent)',                                  },
	info:                                 { name: l10n.t('Info'),                           label: '$(info)',                                    },
  insert:                               { name: l10n.t('Insert'),                         label: '$(insert)',                                  },
	issueClosed:                          { name: l10n.t('Issue Closed'),                   label: '$(issue-closed)',                            },
  issueDraft:                           { name: l10n.t('Issue Draft'),                    label: '$(issue-draft)',                             },
	issueOpened:                          { name: l10n.t('Issue Opened'),                   label: '$(issue-opened)',                            },
	issueReopened:                        { name: l10n.t('Issue Reopened'),                 label: '$(issue-reopened)',                          },
	issues:                               { name: l10n.t('Issues'),                         label: '$(issues)',                                  },
	italic:                               { name: l10n.t('Italic'),                         label: '$(italic)',                                  },
	jersey:                               { name: l10n.t('Jersey'),                         label: '$(jersey)',                                  },
	json:                                 { name: l10n.t('Json'),                           label: '$(json)',                                    },
} as const;

export default icons;
