import { l10n } from 'vscode';

const icons = {
	package:                              { name: l10n.t('Package'),              label: '$(package)',                                 },
	paintcan:                             { name: l10n.t('Paintcan'),             label: '$(paintcan)',                                },
	pass:                                 { name: l10n.t('Pass'),                 label: '$(pass)',                                    },
	passFilled:                           { name: l10n.t('Pass Filled'),          label: '$(pass-filled)',                             },
	pencil:                               { name: l10n.t('Pencil'),               label: '$(pencil)',                                  },
	person:                               { name: l10n.t('Person'),               label: '$(person)',                                  },
	personAdd:                            { name: l10n.t('Person Add'),           label: '$(person-add)',                              },
	personFilled:                         { name: l10n.t('Person Filled'),        label: '$(person-filled)',                           },
	personFollow:                         { name: l10n.t('Person Follow'),        label: '$(person-follow)',                           },
	personOutline:                        { name: l10n.t('Person Outline'),       label: '$(person-outline)',                          },
  pieChart:                             { name: l10n.t('PieChart'),             label: '$(pie-chart)',                               },
  piano:                                { name: l10n.t('Piano'),                label: '$(piano)',                                   },
	pin:                                  { name: l10n.t('Pin'),                  label: '$(pin)',                                     },
	pinned:                               { name: l10n.t('Pinned'),               label: '$(pinned)',                                  },
	pinnedDirty:                          { name: l10n.t('Pinned Dirty'),         label: '$(pinned-dirty)',                            },
	play:                                 { name: l10n.t('Play'),                 label: '$(play)',                                    },
	playCircle:                           { name: l10n.t('Play Circle'),          label: '$(play-circle)',                             },
	plug:                                 { name: l10n.t('Plug'),                 label: '$(plug)',                                    },
	plus:                                 { name: l10n.t('Plus'),                 label: '$(plus)',                                    },
	preserveCase:                         { name: l10n.t('Preserve Case'),        label: '$(preserve-case)',                           },
	preview:                              { name: l10n.t('Preview'),              label: '$(preview)',                                 },
	primitiveDot:                         { name: l10n.t('Primitive Dot'),        label: '$(primitive-dot)',                           },
	primitiveSquare:                      { name: l10n.t('Primitive Square'),     label: '$(primitive-square)',                        },
	project:                              { name: l10n.t('Project'),              label: '$(project)',                                 },
	pulse:                                { name: l10n.t('Pulse'),                label: '$(pulse)',                                   },
	question:                             { name: 'Question',                     label: '$(question)',                                },
	quote:                                { name: l10n.t('Quote'),                label: '$(quote)',                                   },
	radioTower:                           { name: l10n.t('Radio Tower'),          label: '$(radio-tower)',                             },
	reactions:                            { name: l10n.t('Reactions'),            label: '$(reactions)',                               },
	record:                               { name: l10n.t('Record'),               label: '$(record)',                                  },
	recordKeys:                           { name: l10n.t('Record Keys'),          label: '$(record-keys)',                             },
  recordSmall:                          { name: l10n.t('Record Small'),         label: '$(record-small)',                            },
	redo:                                 { name: l10n.t('Redo'),                 label: '$(redo)',                                    },
	references:                           { name: l10n.t('References'),           label: '$(references)',                              },
	refresh:                              { name: l10n.t('Refresh'),              label: '$(refresh)',                                 },
	regex:                                { name: l10n.t('Regex'),                label: '$(regex)',                                   },
	remote:                               { name: l10n.t('Remote'),               label: '$(remote)',                                  },
	remoteExplorer:                       { name: l10n.t('Remote Explorer'),      label: '$(remote-explorer)',                         },
	remove:                               { name: l10n.t('Remove'),               label: '$(remove)',                                  },
	removeClose:                          { name: l10n.t('Remove Close'),         label: '$(remove-close)',                            },
	repl:                                 { name: l10n.t('Repl'),                 label: '$(repl)',                                    },
	replace:                              { name: l10n.t('Replace'),              label: '$(replace)',                                 },
	replaceAll:                           { name: l10n.t('Replace All'),          label: '$(replace-all)',                             },
	reply:                                { name: l10n.t('Reply'),                label: '$(reply)',                                   },
	repo:                                 { name: l10n.t('Repo'),                 label: '$(repo)',                                    },
	repoClone:                            { name: l10n.t('Repo Clone'),           label: '$(repo-clone)',                              },
	repoCreate:                           { name: l10n.t('Repo Create'),          label: '$(repo-create)',                             },
	repoDelete:                           { name: l10n.t('Repo Delete'),          label: '$(repo-delete)',                             },
	repoForcePush:                        { name: l10n.t('Repo Force Push'),      label: '$(repo-force-push)',                         },
	repoForked:                           { name: l10n.t('Repo Forked'),          label: '$(repo-forked)',                             },
	repoPull:                             { name: l10n.t('Repo Pull'),            label: '$(repo-pull)',                               },
	repoPush:                             { name: l10n.t('Repo Push'),            label: '$(repo-push)',                               },
	repoSync:                             { name: l10n.t('Repo Sync'),            label: '$(repo-sync)',                               },
	report:                               { name: l10n.t('Report'),               label: '$(report)',                                  },
	requestChanges:                       { name: l10n.t('Request Changes'),      label: '$(request-changes)',                         },
	rocket:                               { name: l10n.t('Rocket'),               label: '$(rocket)',                                  },
	rootFolder:                           { name: l10n.t('Root Folder'),          label: '$(root-folder)',                             },
	rootFolderOpened:                     { name: l10n.t('Root Folder Opened'),   label: '$(root-folder-opened)',                      },
	rss:                                  { name: l10n.t('RSS'),                  label: '$(rss)',                                     },
	ruby:                                 { name: l10n.t('Ruby'),                 label: '$(ruby)',                                    },
	run:                                  { name: l10n.t('Run'),                  label: '$(run)',                                     },
	runAll:                               { name: l10n.t('Run All'),              label: '$(run-all)',                                 },
	runAbove:                             { name: l10n.t('Run Above'),            label: '$(run-above)',                               },
	runBelow:                             { name: l10n.t('Run Below'),            label: '$(run-below)',                               },
  runErrors:                            { name: l10n.t('Run Errors'),           label: '$(run-errors)',                              },
	save:                                 { name: 'Save',                         label: '$(save)',                                    },
	saveAll:                              { name: l10n.t('Save All'),             label: '$(save-all)',                                },
	saveAs:                               { name: l10n.t('Save As'),              label: '$(save-as)',                                 },
	screenFull:                           { name: l10n.t('Screen Full'),          label: '$(screen-full)',                             },
	screenNormal:                         { name: l10n.t('Screen Normal'),        label: '$(screen-normal)',                           },
	search:                               { name: l10n.t('Search'),               label: '$(search)',                                  },
	searchSave:                           { name: l10n.t('Search Save'),          label: '$(search-save)',                             },
	searchStop:                           { name: l10n.t('Search Stop'),          label: '$(search-stop)',                             },
  searchFuzzy:                          { name: l10n.t('Search Fuzzy'),         label: '$(search-fuzzy)',                            },
	selection:                            { name: l10n.t('Selection'),            label: '$(selection)',                               },
  send:                                 { name: l10n.t('Send'),                 label: '$(send)',                                    },
	server:                               { name: l10n.t('Server'),               label: '$(server)',                                  },
	serverEnvironment:                    { name: l10n.t('Server Environment'),   label: '$(server-environment)',                      },
	serverProcess:                        { name: l10n.t('Server Process'),       label: '$(server-process)',                          },
	settings:                             { name: l10n.t('Settings'),             label: '$(settings)',                                },
	settingsGear:                         { name: l10n.t('Settings Gear'),        label: '$(settings-gear)',                           },
	shield:                               { name: l10n.t('Shield'),               label: '$(shield)',                                  },
	signIn:                               { name: l10n.t('Sign In'),              label: '$(sign-in)',                                 },
	signOut:                              { name: l10n.t('Sign Out'),             label: '$(sign-out)',                                },
	smiley:                               { name: l10n.t('Smiley'),               label: '$(smiley)',                                  },
  snake:                                { name: l10n.t('Snake'),                label: '$(snake)',                                   },
  sparkle:                              { name: l10n.t('Sparkle'),              label: '$(sparkle)',                                 },
	sortPrecedence:                       { name: l10n.t('Sort Precedence'),      label: '$(sort-precedence)',                         },
	sourceControl:                        { name: l10n.t('Soruce Control'),       label: '$(source-control)',                          },
	splitHorizontal:                      { name: l10n.t('Split Horizontal'),     label: '$(split-horizontal)',                        },
	splitVertical:                        { name: l10n.t('Split Vertical'),       label: '$(split-vertical)',                          },
	squirrel:                             { name: l10n.t('Squirrel'),             label: '$(squirrel)',                                },
	star:                                 { name: l10n.t('Star'),                 label: '$(star)',                                    },
	starAdd:                              { name: l10n.t('Star Add'),             label: '$(star-add)',                                },
	starDelete:                           { name: l10n.t('Star Delete'),          label: '$(star-delete)',                             },
	starEmpty:                            { name: l10n.t('Star Empty'),           label: '$(star-empty)',                              },
	starFull:                             { name: l10n.t('Star Full'),            label: '$(star-full)',                               },
	starHalf:                             { name: l10n.t('Star Half'),            label: '$(star-half)',                               },
	stop:                                 { name: l10n.t('Stop'),                 label: '$(stop)',                                    },
	stopCircle:                           { name: l10n.t('Stop Circle'),          label: '$(stop-circle)',                             },
	symbolArray:                          { name: l10n.t('Symbol Array'),         label: '$(symbol-array)',                            },
	symbolBoolean:                        { name: l10n.t('Symbol Boolean'),       label: '$(symbol-boolean)',                          },
	symbolClass:                          { name: l10n.t('Symbol Class'),         label: '$(symbol-class)',                            },
	symbolColor:                          { name: l10n.t('Symbol Color'),         label: '$(symbol-color)',                            },
	symbolConstant:                       { name: l10n.t('Symbol Constant'),      label: '$(symbol-constant)',                         },
	symbolConstructor:                    { name: l10n.t('Symbol Constructor'),   label: '$(symbol-constructor)',                      },
	symbolEnum:                           { name: l10n.t('Symbol Enum'),          label: '$(symbol-enum)',                             },
	symbolEnumMember:                     { name: l10n.t('Symbol Enum Menber'),   label: '$(symbol-enum-member)',                      },
	symbolEvent:                          { name: l10n.t('Symbol Event'),         label: '$(symbol-event)',                            },
	symbolField:                          { name: l10n.t('Symbol Field'),         label: '$(symbol-field)',                            },
	symbolFile:                           { name: l10n.t('Symbol File'),          label: '$(symbol-file)',                             },
	symbolFolder:                         { name: l10n.t('Symbol Folder'),        label: '$(symbol-folder)',                           },
	symbolFunction:                       { name: l10n.t('Symbol Function'),      label: '$(symbol-function)',                         },
	symbolInterface:                      { name: l10n.t('Symbol Interface'),     label: '$(symbol-interface)',                        },
	symbolKey:                            { name: l10n.t('Symbol Key'),           label: '$(symbol-key)',                              },
	symbolKeyword:                        { name: l10n.t('Symbol Keyword'),       label: '$(symbol-keyword)',                          },
	symbolMethod:                         { name: l10n.t('Symbol Method'),        label: '$(symbol-method)',                           },
	symbolMisc:                           { name: l10n.t('Symbol Misc'),          label: '$(symbol-misc)',                             },
	symbolModule:                         { name: l10n.t('Symbol Module'),        label: '$(symbol-module)',                           },
	symbolNamespace:                      { name: l10n.t('Symbol Namespace'),     label: '$(symbol-namespace)',                        },
	symbolNull:                           { name: l10n.t('Symbol Null'),          label: '$(symbol-null)',                             },
	symbolNumber:                         { name: l10n.t('Symbol Number'),        label: '$(symbol-number)',                           },
	symbolNumeric:                        { name: l10n.t('Symbol Numeric'),       label: '$(symbol-numeric)',                          },
	symbolObject:                         { name: l10n.t('Symbol Object'),        label: '$(symbol-object)',                           },
	symbolOperator:                       { name: l10n.t('Symbol Operator'),      label: '$(symbol-operator)',                         },
	symbolPackage:                        { name: l10n.t('Symbol Package'),       label: '$(symbol-package)',                          },
	symbolParameter:                      { name: l10n.t('Symbol Parameter'),     label: '$(symbol-parameter)',                        },
	symbolProperty:                       { name: l10n.t('Symbol Property'),      label: '$(symbol-property)',                         },
	symbolReference:                      { name: l10n.t('Symbol Reference'),     label: '$(symbol-reference)',                        },
	symbolRuler:                          { name: l10n.t('Symbol Ruler'),         label: '$(symbol-ruler)',                            },
	symbolSnippet:                        { name: l10n.t('Symbol Snippet'),       label: '$(symbol-snippet)',                          },
	symbolString:                         { name: l10n.t('Symbol String'),        label: '$(symbol-string)',                           },
	symbolStruct:                         { name: l10n.t('Symbol Struct'),        label: '$(symbol-struct)',                           },
	symbolStructure:                      { name: l10n.t('Symbol Structure'),     label: '$(symbol-structure)',                        },
	symbolText:                           { name: l10n.t('Symbol Text'),          label: '$(symbol-text)',                             },
	symbolTypeParameter:                  { name: l10n.t('Symbol Type Prameter'), label: '$(symbol-type-parameter)',                   },
	symbolUnit:                           { name: l10n.t('Symbol Unit'),          label: '$(symbol-unit)',                             },
	symbolValue:                          { name: l10n.t('Symbol Value'),         label: '$(symbol-value)',                            },
	symbolVariable:                       { name: l10n.t('Symbol Variable'),      label: '$(symbol-variable)',                         },
	sync:                                 { name: l10n.t('Sync'),                 label: '$(sync)',                                    },
	syncIgnored:                          { name: l10n.t('Sync Ignored'),         label: '$(sync-ignored)',                            },
	tagAdd:                               { name: l10n.t('Tag Add'),              label: '$(tag-add)',                                 },
	tagRemove:                            { name: l10n.t('Tag Remove'),           label: '$(tag-remove)',                              },
	tag:                                  { name: l10n.t('Tag'),                  label: '$(tag)',                                     },
	target:                               { name: l10n.t('Target'),               label: '$(target)',                                  },
	tasklist:                             { name: l10n.t('Tasklist'),             label: '$(tasklist)',                                },
	telescope:                            { name: l10n.t('Telescope'),            label: '$(telescope)',                               },
	terminalBash:                         { name: l10n.t('Terminal Bash'),        label: '$(terminal-bash)',                           },
	terminalCmd:                          { name: l10n.t('Terminal Cmd'),         label: '$(terminal-cmd)',                            },
	terminalDebian:                       { name: l10n.t('Terminal Debian'),      label: '$(terminal-debian)',                         },
	terminalLinux:                        { name: l10n.t('Terminal Linux'),       label: '$(terminal-linux)',                          },
	terminalPowershell:                   { name: l10n.t('Terminal Powershell'),  label: '$(terminal-powershell)',                     },
	terminalTmux:                         { name: l10n.t('Terminal Tmux'),        label: '$(terminal-tmux)',                           },
	terminalUbuntu:                       { name: l10n.t('Terminal Ubuntu'),      label: '$(terminal-ubuntu)',                         },
	terminal:                             { name: l10n.t('Terminal'),             label: '$(terminal)',                                },
	textSize:                             { name: l10n.t('Text Size'),            label: '$(text-size)',                               },
	threeBars:                            { name: l10n.t('Three Bars'),           label: '$(three-bars)',                              },
	thumbsdown:                           { name: l10n.t('Thumbsdown'),           label: '$(thumbsdown)',                              },
  thumbsdownFilled:                     { name: l10n.t('Thumbsdown Filled'),    label: '$(thumbsdown-filled)',                       },
	thumbsup:                             { name: l10n.t('Thumbsup'),             label: '$(thumbsup)',                                },
	thumbsupFilled:                       { name: l10n.t('Thumbsup Filled'),      label: '$(thumbsup-filled)',                         },
	tools:                                { name: l10n.t('Tools'),                label: '$(tools)',                                   },
  trash:                                { name: l10n.t('Trash'),                label: '$(trash)',                                   },
	trashcan:                             { name: l10n.t('Trashcan'),             label: '$(trashcan)',                                },
	triangleDown:                         { name: l10n.t('Triangle Down'),        label: '$(triangle-down)',                           },
	triangleLeft:                         { name: l10n.t('Triangle Left'),        label: '$(triangle-left)',                           },
	triangleRight:                        { name: l10n.t('Triangle Right'),       label: '$(triangle-right)',                          },
	triangleUp:                           { name: l10n.t('Triangle Up'),          label: '$(triangle-up)',                             },
	twitter:                              { name: l10n.t('Twitter'),              label: '$(twitter)',                                 },
	typeHierarchy:                        { name: l10n.t('Type Hierarchy'),       label: '$(type-hierarchy)',                          },
	typeHierarchySub:                     { name: l10n.t('Type Hierarchy Sub'),   label: '$(type-hierarchy-sub)',                      },
	typeHierarchySuper:                   { name: l10n.t('Type Hierarchy Super'), label: '$(type-hierarchy-super)',                    },
} as const;

export default icons;
