export const icons = {
	account:                              { name: 'Account',                                  label: '$(account)',                                 description: 'account' },
	activateBreakpoints:                  { name: 'Activate Breakpoints',                     label: '$(activate-breakpoints)',                    description: 'activate-breakpoints' },
	add:                                  { name: 'Add',                                      label: '$(add)',                                     description: 'add' },
	alert:                                { name: 'Alert',                                    label: '$(alert)',                                   description: 'alert' },
	archive:                              { name: 'Archive',                                  label: '$(archive)',                                 description: 'archive' },
	array:                                { name: 'Array',                                    label: '$(array)',                                   description: 'array' },
	arrowBoth:                            { name: 'Arrow Both',                               label: '$(arrow-both)',                              description: 'arrow-both' },
	arrowDown:                            { name: 'Arrow Down',                               label: '$(arrow-down)',                              description: 'arrow-down' },
	arrowLeft:                            { name: 'Arrow Left',                               label: '$(arrow-left)',                              description: 'arrow-left' },
	arrowRight:                           { name: 'Arrow Right',                              label: '$(arrow-right)',                             description: 'arrow-right' },
	arrowSmallDown:                       { name: 'Arrow Small Down',                         label: '$(arrow-small-down)',                        description: 'arrow-small-down' },
	arrowSmallLeft:                       { name: 'Arrow Small Left',                         label: '$(arrow-small-left)',                        description: 'arrow-small-left' },
	arrowSmallRight:                      { name: 'Arrow Small Right',                        label: '$(arrow-small-right)',                       description: 'arrow-small-right' },
	arrowSmallUp:                         { name: 'Arrow Small Up',                           label: '$(arrow-small-up)',                          description: 'arrow-small-up' },
	arrowUp:                              { name: 'Arrow Up',                                 label: '$(arrow-up)',                                description: 'arrow-up' },
	beaker:                               { name: 'Beaker',                                   label: '$(beaker)',                                  description: 'beaker' },
	bell:                                 { name: 'Bell',                                     label: '$(bell)',                                    description: 'bell' },
	bellDot:                              { name: 'Bell Dot',                                 label: '$(bell-dot)',                                description: 'bell-dot' },
	bold:                                 { name: 'Bold',                                     label: '$(bold)',                                    description: 'bold' },
	book:                                 { name: 'Book',                                     label: '$(book)',                                    description: 'book' },
	bookmark:                             { name: 'Bookmark',                                 label: '$(bookmark)',                                description: 'bookmark' },
	briefcase:                            { name: 'Briefcase',                                label: '$(briefcase)',                               description: 'briefcase' },
	broadcast:                            { name: 'Broadcast',                                label: '$(broadcast)',                               description: 'broadcast' },
	browser:                              { name: 'Browser',                                  label: '$(browser)',                                 description: 'browser' },
	bug:                                  { name: 'Bug',                                      label: '$(bug)',                                     description: 'bug' },
	calendar:                             { name: 'Calendar',                                 label: '$(calendar)',                                description: 'calendar' },
	callIncoming:                         { name: 'Call In Coming',                           label: '$(call-incoming)',                           description: 'call-incoming' },
	callOutgoing:                         { name: 'Call Out going',                           label: '$(call-outgoing)',                           description: 'call-outgoing' },
	caseSensitive:                        { name: 'Case Sensitive',                           label: '$(case-sensitive)',                          description: 'case-sensitive' },
	check:                                { name: 'Check',                                    label: '$(check)',                                   description: 'check' },
	checkAll:                             { name: 'Check All',                                label: '$(check-all)',                               description: 'check-all' },
	checklist:                            { name: 'Checklist',                                label: '$(checklist)',                               description: 'checklist' },
	chevronDown:                          { name: 'Chevron Down',                             label: '$(chevron-down)',                            description: 'chevron-down' },
	chevronLeft:                          { name: 'Chevron Left',                             label: '$(chevron-left)',                            description: 'chevron-left' },
	chevronRight:                         { name: 'Chevron Right',                            label: '$(chevron-right)',                           description: 'chevron-right' },
	chevronUp:                            { name: 'Chevron Up',                               label: '$(chevron-up)',                              description: 'chevron-up' },
	chromeClose:                          { name: 'Chrome Close',                             label: '$(chrome-close)',                            description: 'chrome-close' },
	chromeMaximize:                       { name: 'Chrome Maximize',                          label: '$(chrome-maximize)',                         description: 'chrome-maximize' },
	chromeMinimize:                       { name: 'Cherme Minimize',                          label: '$(chrome-minimize)',                         description: 'chrome-minimize' },
	chromeRestore:                        { name: 'Chrome Restore',                           label: '$(chrome-restore)',                          description: 'chrome-restore' },
	circleFilled:                         { name: 'Chrome Filled',                            label: '$(circle-filled)',                           description: 'circle-filled' },
	circleLargeFilled:                    { name: 'Circle Large Filled',                      label: '$(circle-large-filled)',                     description: 'circle-large-filled' },
	circleLargeOutline:                   { name: 'Circle Large Outline',                     label: '$(circle-large-outline)',                    description: 'circle-large-outline' },
	circleOutline:                        { name: 'Circle Outline',                           label: '$(circle-outline)',                          description: 'circle-outline' },
	circleSlash:                          { name: 'Circle Slash',                             label: '$(circle-slash)',                            description: 'circle-slash' },
	circuitBoard:                         { name: 'Circuit Board',                            label: '$(circuit-board)',                           description: 'circuit-board' },
	clearAll:                             { name: 'Clear All',                                label: '$(clear-all)',                               description: 'clear-all' },
	clippy:                               { name: 'Clippy',                                   label: '$(clippy)',                                  description: 'clippy' },
	clock:                                { name: 'Clock',                                    label: '$(clock)',                                   description: 'clock' },
	clone:                                { name: 'Clone',                                    label: '$(clone)',                                   description: 'clone' },
	close:                                { name: 'Close',                                    label: '$(close)',                                   description: 'close' },
	closeAll:                             { name: 'Close All',                                label: '$(close-all)',                               description: 'close-all' },
	closeDirty:                           { name: 'Close Dirty',                              label: '$(close-dirty)',                             description: 'close-dirty' },
	cloud:                                { name: 'Cloud',                                    label: '$(cloud)',                                   description: 'cloud' },
	cloudDownload:                        { name: 'Cloud Download',                           label: '$(cloud-download)',                          description: 'cloud-download' },
	cloudUpload:                          { name: 'Cloud Upload',                             label: '$(cloud-upload)',                            description: 'cloud-upload' },
	code:                                 { name: 'Code',                                     label: '$(code)',                                    description: 'code' },
	collapseAll:                          { name: 'Collapse All',                             label: '$(collapse-all)',                            description: 'collapse-all' },
	colorMode:                            { name: 'Color Mode',                               label: '$(color-mode)',                              description: 'color-mode' },
	combine:                              { name: 'Combine',                                  label: '$(combine)',                                 description: 'combine' },
	comment:                              { name: 'Comment',                                  label: '$(comment)',                                 description: 'comment' },
	commentAdd:                           { name: 'Comment Add',                              label: '$(comment-add)',                             description: 'comment-add' },
	commentDiscussion:                    { name: 'Comment Disucussion',                      label: '$(comment-discussion)',                      description: 'comment-discussion' },
	compareChanges:                       { name: 'Compare Change',                           label: '$(compare-changes)',                         description: 'compare-changes' },
	console:                              { name: 'Console',                                  label: '$(console)',                                 description: 'console' },
	creditCard:                           { name: 'Credit Card',                              label: '$(credit-card)',                             description: 'credit-card' },
	dash:                                 { name: 'Dash',                                     label: '$(dash)',                                    description: 'dash' },
	dashboard:                            { name: 'Dashboard',                                label: '$(dashboard)',                               description: 'dashboard' },
	database:                             { name: 'Datebase',                                 label: '$(database)',                                description: 'database' },
	debug:                                { name: 'Debug',                                    label: '$(debug)',                                   description: 'debug' },
	debugAlt:                             { name: 'Debug Alt',                                label: '$(debug-alt)',                               description: 'debug-alt' },
	debugAltSmall:                        { name: 'Debug Alt Small',                          label: '$(debug-alt-small)',                         description: 'debug-alt-small' },
	debugBreakpoint:                      { name: 'Debug Breakpoint',                         label: '$(debug-breakpoint)',                        description: 'debug-breakpoint' },
	debugBreakpointConditional:           { name: 'Debug Breakpoint Conditional',             label: '$(debug-breakpoint-conditional)',            description: 'debug-breakpoint-conditional' },
	debugBreakpointConditionalDisabled :  { name: 'Debug Breakpoint Conditional Disabled',    label: '$(debug-breakpoint-conditional-disabled)',   description: 'debug-breakpoint-conditional-disabled' },
	debugBreakpointConditionalUnverified: { name: 'Debug Breakpoint Conditional Univerified', label: '$(debug-breakpoint-conditional-unverified)', description: 'debug-breakpoint-conditional-unverified' },
	debugBreakpointData:                  { name: 'Debug Breakpoint Data',                    label: '$(debug-breakpoint-data)',                   description: 'debug-breakpoint-data' },
	debugBreakpointDataDisabled:          { name: 'Debug Breakpoint Data Disbaled',           label: '$(debug-breakpoint-data-disabled)',          description: 'debug-breakpoint-data-disabled' },
	debugBreakpointDataUnverified:        { name: 'Debug Breakpoint Data Unverified',         label: '$(debug-breakpoint-data-unverified)',        description: 'debu-breakpoint-data-unverified' },
	debugBreakpointDisabled:              { name: 'Debug Breakpoint Disabled',                label: '$(debug-breakpoint-disabled)',               description: 'debug-breakpoint-disablde' },
	debugBreakpointFunction:              { name: 'Debug Breakpoint Function',                label: '$(debug-breakpoint-function)',               description: 'debug-breakpoint-function' },
	debugBreakpointFunctionDisabled:      { name: 'Debug Breakpoint Function Disabled',       label: '$(debug-breakpoint-function-disabled)',      description: 'debug-breakpoint-function-disabled' },
	debugBreakpointFunctionUnverified:    { name: 'Debug Breakpoint Function Unverified',     label: '$(debug-breakpoint-function-unverified)',    description: 'debug-breakpoint-function-unverified' },
	debugBreakpointLog:                   { name: 'Debug Breakpoint Log',                     label: '$(debug-breakpoint-log)',                    description: 'debug-breakpoint-log' },
	debugBreakpointLogDisabled:           { name: 'Debug Breakpoint Log Disabled',            label: '$(debug-breakpoint-log-disabled)',           description: 'debug-breakpoint-log-disabled' },
	debugBreakpointLogUnverified:         { name: 'Debug Breakpoint Log Unverified',          label: '$(debug-breakpoint-log-unverified)',         description: 'debug-breakpoint-log-unverified' },
	debugBreakpointUnsupported:           { name: 'Debug Breakpoint Unsupported',             label: '$(debug-breakpoint-unsupported)',            description: 'debug-breakpoint-unsupported' },
	debugBreakpointUnverified:            { name: 'Debug Breakpoint Unverified',              label: '$(debug-breakpoint-unverified)',             description: 'debug-breakpoint-unverified' },
	debugConsole:                         { name: 'Debug Console',                            label: '$(debug-console)',                           description: 'debug-console' },
	debugContinue:                        { name: 'Debug Continue',                           label: '$(debug-continue)',                          description: 'debug-continue' },
	debugDisconnect:                      { name: 'Debug Disconnect',                         label: '$(debug-disconnect)',                        description: 'debug-disconnect' },
	debugHint:                            { name: 'Debug Hint',                               label: '$(debug-hint)',                              description: 'debug-hint' },
	debugPause:                           { name: 'Debug Pause',                              label: '$(debug-pause)',                             description: 'dubug-pause' },
	debugRerun:                           { name: 'Debug Rerun',                              label: '$(debug-rerun)',                             description: 'debug-rerun' },
	debugRestertFrame:                    { name: 'Debug Restart Frame',                      label: '$(debug-restart-frame)',                     description: 'debug-restart-frame' },
	debugReverseContinue:                 { name: 'Debug Reverse Continue',                   label: '$(debug-reverse-continue)',                  description: 'debug-reverse-continue' },
	debugStackframe:                      { name: 'Debug Stackframe',                         label: '$(debug-stackframe)',                        description: 'debug-stackframe' },
	debugStackframeActive:                { name: 'Debug Stackframe Active',                  label: '$(debug-stackframe-active)',                 description: 'debug-stackframe-active' },
	debugStackframeDot:                   { name: 'Debug Stackframe Dot',                     label: '$(debug-stackframe-dot)',                    description: 'debug-stackframe-dot' },
	debugStackframeFocused:               { name: 'Debug Stackframe Focused',                 label: '$(debug-stackframe-focused)',                description: 'debug-stackframe-focused' },
	debugStart:                           { name: 'Debug Start',                              label: '$(debug-start)',                             description: 'debug-start' },
	debugStepBack:                        { name: 'Debug Step Back',                          label: '$(debug-step-back)',                         description: 'debug-step-back' },
	debugStepInto:                        { name: 'Debug Step Into',                          label: '$(debug-step-into)',                         description: 'debug-step-into' },
	debugStepOut:                         { name: 'Debug Step Out',                           label: '$(debug-step-out)',                          description: 'debug-step-out' },
	debugStepOver:                        { name: 'Debug Step Over',                          label: '$(debug-step-over)',                         description: 'debug-step-over' },
	debugStop:                            { name: 'Debug Stop',                               label: '$(debug-stop)',                              description: 'debug-stop' },
	desktopDownload:                      { name: 'Desktop Download',                         label: '$(desktop-download)',                        description: 'desktop-download' },
	deviceCamera:                         { name: 'Device Camera',                            label: '$(device-camera)',                           description: 'device-camera' },
	deviceCameraVideo:                    { name: 'Device Camera Video',                      label: '$(device-camera-video)',                     description: 'device-camera-video' },
	deviceDesktop:                        { name: 'Device Desktop',                           label: '$(device-desktop)',                          description: 'device-desktop' },
	deviceMobile:                         { name: 'Device Mobile',                            label: '$(device-mobile)',                           description: 'device-mobile' },
	diff:                                 { name: 'Diff',                                     label: '$(diff)',                                    description: 'diff' },
	diffAdded:                            { name: 'Diff Added',                               label: '$(diff-added)',                              description: 'diff-added' },
	diffIgnored:                          { name: 'Diff Ignored',                             label: '$(diff-ignored)',                            description: 'diff-ignored' },
	diffModified:                         { name: 'Diff Modified',                            label: '$(diff-modified)',                           description: 'diff-modified' },
	diffRemoved:                          { name: 'Diff Removed',                             label: '$(diff-removed)',                            description: 'diff-removed' },
	diffRenamed:                          { name: 'Diff Renamed',                             label: '$(diff-renamed)',                            description: 'diff-renamed' },
	discard:                              { name: 'Discard',                                  label: '$(discard)',                                 description: 'discard' },
	dropDownButton:                       { name: 'Drop Down Button',                         label: '$(drop-down-button)',                        description: 'drop-down-button'},
	edit:                                 { name: 'Edit',                                     label: '$(edit)',                                    description: 'edit' },
	editorLayout:                         { name: 'Editor Layout',                            label: '$(editor-layout)',                           description: 'editor-layout' },
	ellipsis:                             { name: 'Ellipsis',                                 label: '$(ellipsis)',                                description: 'ellipsis' },
	emptyWindow:                          { name: 'Empty Window',                             label: '$(empty-window)',                            description: 'empty-window' },
	error:                                { name: 'Error',                                    label: '$(error)',                                   description: 'error' },
	exclude:                              { name: 'Exclude',                                  label: '$(exclude)',                                 description: 'exclude' },
	expandAll:                            { name: 'Expand All',                               label: '$(expand-all)',                              description: 'expand-all' },
	export:                               { name: 'Export',                                   label: '$(export)',                                  description: 'export' },
	extensions:                           { name: 'Extensions',                               label: '$(extensions)',                              description: 'extensions' },
	eye:                                  { name: 'Eye',                                      label: '$(eye)',                                     description: 'eye' },
	eyeClosed:                            { name: 'Eye Closed',                               label: '$(eye-closed)',                              description: 'eye-closed' },
	eyeUnwatch:                           { name: 'Eye Unwatch',                              label: '$(eye-unwatch)',                             description: 'eye-unwatch' },
	eyeWatch:                             { name: 'Eye Watch',                                label: '$(eye-watch)',                               description: 'eye-watch' },
};
