export const icons = {
	feedback:                             { name: 'Feedback',                   label: '$(feedback)',                                description: 'feedback' },
	file:                                 { name: 'File',                       label: '$(file)',                                    description: 'file' },
	fileAdd:                              { name: 'File Add',                   label: '$(file-add)',                                description: 'file-add' },
	fileBinaly:                           { name: 'File Binaly',                label: '$(file-binary)',                             description: 'file-binary' },
	fileCode:                             { name: 'File Code',                  label: '$(file-code)',                               description: 'file-code' },
	fileDirectory:                        { name: 'File Directory',             label: '$(file-directory)',                          description: 'file-directory' },
	fileDirectoryCreate:                  { name: 'File Directory Create',      label: '$(file-directory-create)',                   description: 'file-directory-create' },
	fileMedia:                            { name: 'File Media',                 label: '$(file-media)',                              description: 'file-media' },
	filePdf:                              { name: 'File PDF',                   label: '$(file-pdf)',                                description: 'file-pdf' },
	fileSubmodule:                        { name: 'File Submodule',             label: '$(file-submodule)',                          description: 'file-submodule' },
	fileSymlinkDirectory:                 { name: 'File Symlink Directory',     label: '$(file-symlink-directory)',                  description: 'file-symlink-directory' },
	fileSymlinkFile:                      { name: 'File Symlink File',          label: '$(file-symlink-file)',                       description: 'file-symlink-file' },
	fileText:                             { name: 'File Text',                  label: '$(file-text)',                               description: 'file-text' },
	fileZip:                              { name: 'File Zip',                   label: '$(file-zip)',                                description: 'file-zip' },
	files:                                { name: 'Files',                      label: '$(files)',                                   description: 'files' },
	filter:                               { name: 'Filter',                     label: '$(filter)',                                  description: 'filter' },
	flame:                                { name: 'Flame',                      label: '$(flame)',                                   description: 'flame' },
	fold:                                 { name: 'Fold',                       label: '$(fold)',                                    description: 'fold' },
	foldDown:                             { name: 'Fold Down',                  label: '$(fold-down)',                               description: 'fold-down' },
	foldUp:                               { name: 'Fold Up',                    label: '$(fold-up)',                                 description: 'fold-up' },
	folder:                               { name: 'Folder',                     label: '$(folder)',                                  description: 'folder' },
	folderActive:                         { name: 'Folder Active',              label: '$(folder-active)',                           description: 'folder-active' },
	folderOpened:                         { name: 'Folder Opened',              label: '$(folder-opened)',                           description: 'folder-opened' },
	gather:                               { name: 'Gather',                     label: '$(gather)',                                  description: 'gather' },
	gear:                                 { name: 'Gear',                       label: '$(gear)',                                    description: 'gear' },
	gift:                                 { name: 'Gift',                       label: '$(gift)',                                    description: 'gift' },
	gistFork:                             { name: 'Gist Fork',                  label: '$(gist-fork)',                               description: 'gist-fork' },
	gistNew:                              { name: 'Gist New',                   label: '$(gist-new)',                                description: 'gist-new' },
	gistPrivate:                          { name: 'Gist Private',               label: '$(gist-private)',                            description: 'gist-private' },
	gistSecret:                           { name: 'Gist Secret',                label: '$(gist-secret)',                             description: 'gist-secret' },
	gitBranch:                            { name: 'Git Branch',                 label: '$(git-branch)',                              description: 'git-branch' },
	gitBranchCreate:                      { name: 'Git Branch Create',          label: '$(git-branch-create)',                       description: 'git-branch-create' },
	gitBranchDelete:                      { name: 'Git Branch Delete',          label: '$(git-branch-delete)',                       description: 'git-branch-delete' },
	gitCommit:                            { name: 'Git Commit',                 label: '$(git-commit)',                              description: 'git-commit' },
	gitCompare:                           { name: 'Git Compare',                label: '$(git-compare)',                             description: 'git-compare' },
	gitForkPrivate:                       { name: 'Git Fork Private',           label: '$(git-fork-private)',                        description: 'git-fork-private' },
	gitMerge:                             { name: 'Git Merge',                  label: '$(git-merge)',                               description: 'git-merge' },
	gitPullRequest:                       { name: 'Git Pull Request',           label: '$(git-pull-request)',                        description: 'git-pull-request' },
	gitPullRequestAbandoned:              { name: 'Git Pull Request Abandoned', label: '$(git-pull-request-abandoned)',              description: 'git-pull-request-abandoned' },
	gitPullRequestCreate:                 { name: 'Git Pull Request Create',    label: '$(git-pull-request-create)',                 description: 'git-pull-request-create' },
	github:                               { name: 'Github',                     label: '$(github)',                                  description: 'github' },
	githubAction:                         { name: 'Github Action',              label: '$(github-action)',                           description: 'github-action' },
	githubAlt:                            { name: 'Github Alt',                 label: '$(github-alt)',                              description: 'github-alt' },
	githubInverted:                       { name: 'Github Inverted',            label: '$(github-inverted)',                         description: 'github-inverted' },
	globe:                                { name: 'Globe',                      label: '$(globe)',                                   description: 'globe' },
	goToFile:                             { name: 'Go to File',                 label: '$(go-to-file)',                              description: 'go-to-file' },
	grabber:                              { name: 'Grabber',                    label: '$(grabber)',                                 description: 'grabber' },
	graph:                                { name: 'Graph',                      label: '$(graph)',                                   description: 'graph' },
	graphLeft:                            { name: 'Graph Left',                 label: '$(graph-left)',                              description: 'graph-left' },
	gripper:                              { name: 'Gripper',                    label: '$(gripper)',                                 description: 'gripper' },
	groupByRefType:                       { name: 'Group By Ref Type',          label: '$(group-by-ref-type)',                       description: 'group-by-ref-type' },
	heart:                                { name: 'Heart',                      label: '$(heart)',                                   description: 'heart' },
	history:                              { name: 'History',                    label: '$(history)',                                 description: 'history' },
	home:                                 { name: 'Home',                       label: '$(home)',                                    description: 'home' },
	horizontalRule:                       { name: 'Horizontal Rule',            label: '$(horizontal-rule)',                         description: 'horizontal-rule' },
	hubot:                                { name: 'Hubot',                      label: '$(hubot)',                                   description: 'hubot' },
	inbox:                                { name: 'Inbox',                      label: '$(inbox)',                                   description: 'inbox' },
	info:                                 { name: 'Info',                       label: '$(info)',                                    description: 'info' },
	issueClosed:                          { name: 'Issue Closed',               label: '$(issue-closed)',                            description: 'issue-closed' },
	issueOpened:                          { name: 'Issue Opened',               label: '$(issue-opened)',                            description: 'issue-opened' },
	issueReopened:                        { name: 'Issue Reopened',             label: '$(issue-reopened)',                          description: 'issue-reopened' },
	issues:                               { name: 'Issues',                     label: '$(issues)',                                  description: 'issues' },
	italic:                               { name: 'Italic',                     label: '$(italic)',                                  description: 'italic' },
	jersey:                               { name: 'Jersey',                     label: '$(jersey)',                                  description: 'jersey' },
	json:                                 { name: 'Json',                       label: '$(json)',                                    description: 'json' },
};
