export const icons = {
	kebabHorizontal:                      { name: 'Kebab Horizontal',     label: '$(kebab-horizontal)',                        description: 'kebab-horizontal' },
	kebabVertical:                        { name: 'Kebab Vertical',       label: '$(kebab-vertical)',                          description: 'kebab-vertical' },
	key:                                  { name: 'Key',                  label: '$(key)',                                     description: 'key' },
	keyboard:                             { name: 'Keyboard',             label: '$(keyboard)',                                description: 'keyboard' },
	law:                                  { name: 'Law',                  label: '$(law)',                                     description: 'law' },
	library:                              { name: 'Library',              label: '$(library)',                                 description: 'library' },
	lightBulb1:                           { name: 'Light Bulb',           label: '$(light-bulb)',                              description: 'light-bulb' },
	lightBulb2:                           { name: 'Ligth Bulb',           label: '$(lightbulb)',                               description: 'light-bulb' },
	ligthbulbAutofix:                     { name: 'Ligth Bulb Autofix',   label: '$(lightbulb-autofix)',                       description: 'lightbulb-autofix' },
	link:                                 { name: 'Link',                 label: '$(link)',                                    description: 'link' },
	linkExternal:                         { name: 'Link External',        label: '$(link-external)',                           description: 'link-external' },
	listFilter:                           { name: 'List Filter',          label: '$(list-filter)',                             description: 'list-filter' },
	listFlat:                             { name: 'List Flat',            label: '$(list-flat)',                               description: 'list-flat' },
	listOrdered:                          { name: 'List Ordered',         label: '$(list-ordered)',                            description: 'list-ordered' },
	listSelection:                        { name: 'List Selection',       label: '$(list-selection)',                          description: 'list-selection' },
	listTree:                             { name: 'List Tree',            label: '$(list-tree)',                               description: 'list-tree' },
	listUnordered:                        { name: 'List Unordered',       label: '$(list-unordered)',                          description: 'list-unordered' },
	liveShare:                            { name: 'Live Share',           label: '$(live-share)',                              description: 'live-share' },
	loading:                              { name: 'Loading',              label: '$(loading)',                                 description: 'loading' },
	location:                             { name: 'Location',             label: '$(location)',                                description: 'location' },
	lock:                                 { name: 'Lock',                 label: '$(lock)',                                    description: 'lock' },
	logIn:                                { name: 'Login',                label: '$(log-in)',                                  description: 'log-in' },
	logOut:                               { name: 'Logout',               label: '$(log-out)',                                 description: 'log-out' },
	logoGithub:                           { name: 'Logo Github',          label: '$(logo-github)',                             description: 'logo-github' },
	magnet:                               { name: 'Magnet',               label: '$(magnet)',                                  description: 'magnet' },
	mail:                                 { name: 'Mail',                 label: '$(mail)',                                    description: 'mail' },
	mailRead:                             { name: 'Mail Read',            label: '$(mail-read)',                               description: 'mail-read' },
	mailReply:                            { name: 'Mail Reply',           label: '$(mail-reply)',                              description: 'mail-reply' },
	markGithub:                           { name: 'Mark Github',          label: '$(mark-github)',                             description: 'mark-github' },
	markdown:                             { name: 'Markdown',             label: '$(markdown)',                                description: 'markdown' },
	megaphone:                            { name: 'Megaphone',            label: '$(megaphone)',                               description: 'megaphone' },
	mention:                              { name: 'Mention',              label: '$(mention)',                                 description: 'mention' },
	menu:                                 { name: 'Menu',                 label: '$(menu)',                                    description: 'menu' },
	merge:                                { name: 'Merge',                label: '$(merge)',                                   description: 'merge' },
	microScope:                           { name: 'Microscope',           label: '$(microscope)',                              description: 'microscope' },
	milestone:                            { name: 'Milestone',            label: '$(milestone)',                               description: 'milestone' },
	mirror:                               { name: 'Mirror',               label: '$(mirror)',                                  description: 'mirror' },
	mirrorPrivate:                        { name: 'Mirror Private',       label: '$(mirror-private)',                          description: 'mirror-private' },
	mirrorPublic:                         { name: 'Mirror Public',        label: '$(mirror-public)',                           description: 'mirror-public' },
	more:                                 { name: 'More',                 label: '$(more)',                                    description: 'more' },
	mortarBoard:                          { name: 'Mortar Board',         label: '$(mortar-board)',                            description: 'mortar-board' },
	move:                                 { name: 'Move',                 label: '$(move)',                                    description: 'move' },
	multipleWindows:                      { name: 'Multiple Windows',     label: '$(multiple-windows)',                        description: 'mutiple-windows' },
	mute:                                 { name: 'Mute',                 label: '$(mute)',                                    description: 'mute' },
	newFile:                              { name: 'New File',             label: '$(new-file)',                                description: 'new-file' },
	newFolder:                            { name: 'New Folder',           label: '$(new-folder)',                              description: 'new-folder' },
	noNewline:                            { name: 'No Newline',           label: '$(no-newline)',                              description: 'no-newline' },
	note:                                 { name: 'Note',                 label: '$(note)',                                    description: 'note' },
	notebook:                             { name: 'Notebook',             label: '$(notebook)',                                description: 'notebook' },
	notebookTemplate:                     { name: 'Notebook Template',    label: '$(notebook-template)',                       description: 'notebook-template' },
	octoface:                             { name: 'Octoface',             label: '$(octoface)',                                description: 'octoface' },
	openPreview:                          { name: 'Open Preview',         label: '$(open-preview)',                            description: 'open-preview' },
	organization:                         { name: 'Organization',         label: '$(organization)',                            description: 'organization' },
	organizationFilled:                   { name: 'Organization Filled',  label: '$(organization-filled)',                     description: 'organization-filled' },
	organizationOutline:                  { name: 'Organization Outline', label: '$(organization-outline)',                    description: 'organization-outline' },
	output:                               { name: 'Output',               label: '$(output)',                                  description: 'output' },
};
