export const icons = {
	package:                              { name: 'Package',              label: '$(package)',                                 description: 'package' },
	paintcan:                             { name: 'Paintcan',             label: '$(paintcan)',                                description: 'paintcan' },
	pass:                                 { name: 'Pass',                 label: '$(pass)',                                    description: 'pass' },
	passFilled:                           { name: 'Pass Filled',          label: '$(pass-filled)',                             description: 'pass-filled' },
	pencil:                               { name: 'Pencil',               label: '$(pencil)',                                  description: 'pencil' },
	person:                               { name: 'Person',               label: '$(person)',                                  description: 'person' },
	personAdd:                            { name: 'Person Add',           label: '$(person-add)',                              description: 'person-add' },
	personFilled:                         { name: 'Person Filled',        label: '$(person-filled)',                           description: 'person-filled' },
	personFollow:                         { name: 'Person Follow',        label: '$(person-follow)',                           description: 'person-follow' },
	personOutline:                        { name: 'Person Outline',       label: '$(person-outline)',                          description: 'person-outline' },
	pin:                                  { name: 'Pin',                  label: '$(pin)',                                     description: 'pin' },
	pinned:                               { name: 'Pinned',               label: '$(pinned)',                                  description: 'pinned' },
	pinnedDirty:                          { name: 'Pinned Dirty',         label: '$(pinned-dirty)',                            description: 'piined-dirty' },
	play:                                 { name: 'Play',                 label: '$(play)',                                    description: 'play' },
	playCircle:                           { name: 'Play Circle',          label: '$(play-circle)',                             description: 'play-circle' },
	plug:                                 { name: 'Plug',                 label: '$(plug)',                                    description: 'plug' },
	plus:                                 { name: 'Plus',                 label: '$(plus)',                                    description: 'plus' },
	preserveCase:                         { name: 'Preserve Case',        label: '$(preserve-case)',                           description: 'preserve-case' },
	preview:                              { name: 'Preview',              label: '$(preview)',                                 description: 'preview' },
	primitiveDot:                         { name: 'Primitive Dot',        label: '$(primitive-dot)',                           description: 'primitive-dot' },
	primitiveSquare:                      { name: 'Primitive Square',     label: '$(primitive-square)',                        description: 'primitive-square' },
	project:                              { name: 'Project',              label: '$(project)',                                 description: 'project' },
	pulse:                                { name: 'Pulse',                label: '$(pulse)',                                   description: 'pulse' },
	question:                             { name: 'Question',             label: '$(question)',                                description: 'question' },
	quote:                                { name: 'Quote',                label: '$(quote)',                                   description: 'quote' },
	radioTower:                           { name: 'Radio Tower',          label: '$(radio-tower)',                             description: 'radio-tower' },
	reactions:                            { name: 'Reactions',            label: '$(reactions)',                               description: 'reactions' },
	record:                               { name: 'Record',               label: '$(record)',                                  description: 'record' },
	recordKeys:                           { name: 'Record Keys',          label: '$(record-keys)',                             description: 'record-keys' },
	redo:                                 { name: 'Redo',                 label: '$(redo)',                                    description: 'redo' },
	references:                           { name: 'References',           label: '$(references)',                              description: 'references' },
	refresh:                              { name: 'Refresh',              label: '$(refresh)',                                 description: 'refresh' },
	regex:                                { name: 'Regex',                label: '$(regex)',                                   description: 'regex' },
	remote:                               { name: 'Remote',               label: '$(remote)',                                  description: 'remote' },
	remoteExplorer:                       { name: 'Remote Explorer',      label: '$(remote-explorer)',                         description: 'remote-explorer' },
	remove:                               { name: 'Remove',               label: '$(remove)',                                  description: 'remove' },
	removeClose:                          { name: 'Remove Close',         label: '$(remove-close)',                            description: 'remove-close' },
	repl:                                 { name: 'Repl',                 label: '$(repl)',                                    description: 'repl' },
	replace:                              { name: 'Replace',              label: '$(replace)',                                 description: 'replace' },
	replaceAll:                           { name: 'Replace All',          label: '$(replace-all)',                             description: 'replace-all' },
	reply:                                { name: 'Reply',                label: '$(reply)',                                   description: 'reply' },
	repo:                                 { name: 'Repo',                 label: '$(repo)',                                    description: 'repo' },
	repoClone:                            { name: 'Repo Clone',           label: '$(repo-clone)',                              description: 'repo-clone' },
	repoCreate:                           { name: 'Repo Create',          label: '$(repo-create)',                             description: 'repo-create' },
	repoDelete:                           { name: 'Repo Delete',          label: '$(repo-delete)',                             description: 'repo-delete' },
	repoForcePush:                        { name: 'Repo Force Push',      label: '$(repo-force-push)',                         description: 'repo-force-push' },
	repoForked:                           { name: 'Repo Forked',          label: '$(repo-forked)',                             description: 'repo-forked' },
	repoPull:                             { name: 'Repo Pull',            label: '$(repo-pull)',                               description: 'repo-pull' },
	repoPush:                             { name: 'Repo Push',            label: '$(repo-push)',                               description: 'repo-push' },
	repoSync:                             { name: 'Repo Sync',            label: '$(repo-sync)',                               description: 'repo-sync' },
	report:                               { name: 'Report',               label: '$(report)',                                  description: 'report' },
	requestChanges:                       { name: 'Request Changes',      label: '$(request-changes)',                         description: 'request-changes' },
	rocket:                               { name: 'Rocket',               label: '$(rocket)',                                  description: 'rocket' },
	rootFolder:                           { name: 'Root Folder',          label: '$(root-folder)',                             description: 'root-folder' },
	rootFolderOpened:                     { name: 'Root Folder Opened',   label: '$(root-folder-opened)',                      description: 'root-folder-opened' },
	rss:                                  { name: 'RSS',                  label: '$(rss)',                                     description: 'rss' },
	ruby:                                 { name: 'Ruby',                 label: '$(ruby)',                                    description: 'ruby' },
	run:                                  { name: 'Run',                  label: '$(run)',                                     description: 'run' },
	runAll:                               { name: 'Run All',              label: '$(run-all)',                                 description: 'run-all' },
	runAbove:                             { name: 'Run Above',            label: '$(run-above)',                               description: 'run-above' },
	runBelow:                             { name: 'Run Below',            label: '$(run-below)',                               description: 'run-below' },
	save:                                 { name: 'Save',                 label: '$(save)',                                    description: 'save' },
	saveAll:                              { name: 'Save All',             label: '$(save-all)',                                description: 'save-all' },
	saveAs:                               { name: 'Save As',              label: '$(save-as)',                                 description: 'save-as' },
	screenFull:                           { name: 'Screen Full',          label: '$(screen-full)',                             description: 'screen-full' },
	screenNormal:                         { name: 'Screen Normal',        label: '$(screen-normal)',                           description: 'screen-normal' },
	search:                               { name: 'Search',               label: '$(search)',                                  description: 'search' },
	searchSave:                           { name: 'Search Save',          label: '$(search-save)',                             description: 'search-save' },
	searchStop:                           { name: 'Search Stop',          label: '$(search-stop)',                             description: 'search-stop' },
	selection:                            { name: 'Selection',            label: '$(selection)',                               description: 'selection' },
	server:                               { name: 'Server',               label: '$(server)',                                  description: 'server' },
	serverEnvironment:                    { name: 'Server Environment',   label: '$(server-environment)',                      description: 'server-environment' },
	serverProcess:                        { name: 'Server Process',       label: '$(server-process)',                          description: 'server-process' },
	settings:                             { name: 'Settings',             label: '$(settings)',                                description: 'settings' },
	settingsGear:                         { name: 'Settings Gear',        label: '$(settings-gear)',                           description: 'settings-gear' },
	shield:                               { name: 'Shield',               label: '$(shield)',                                  description: 'shield' },
	signIn:                               { name: 'Sign In',              label: '$(sign-in)',                                 description: 'sign-in' },
	signOut:                              { name: 'Sign Out',             label: '$(sign-out)',                                description: 'sign-out' },
	smiley:                               { name: 'Smiley',               label: '$(smiley)',                                  description: 'smiley' },
	sortPrecedence:                       { name: 'Sort Precedence',      label: '$(sort-precedence)',                         description: 'sort-placedence' },
	sourceControl:                        { name: 'Soruce Control',       label: '$(source-control)',                          description: 'source-control' },
	splitHorizontal:                      { name: 'Split Horizontal',     label: '$(split-horizontal)',                        description: 'split-horizontal' },
	splitVertical:                        { name: 'Split Vertical',       label: '$(split-vertical)',                          description: 'split-vertical' },
	squirrel:                             { name: 'Squirrel',             label: '$(squirrel)',                                description: 'squirrel' },
	star:                                 { name: 'Star',                 label: '$(star)',                                    description: 'star' },
	starAdd:                              { name: 'Star Add',             label: '$(star-add)',                                description: 'star-add' },
	starDelete:                           { name: 'Star Delete',          label: '$(star-delete)',                             description: 'star-delete' },
	starEmpty:                            { name: 'Star Empty',           label: '$(star-empty)',                              description: 'star-empty' },
	starFull:                             { name: 'Star Full',            label: '$(star-full)',                               description: 'star-full' },
	starHalf:                             { name: 'Star Half',            label: '$(star-half)',                               description: 'star-half' },
	stop:                                 { name: 'Stop',                 label: '$(stop)',                                    description: 'stop' },
	stopCircle:                           { name: 'Stop Circle',          label: '$(stop-circle)',                             description: 'stop-circle' },
	symbolArray:                          { name: 'Symbol Array',         label: '$(symbol-array)',                            description: 'symbol-array' },
	symbolBoolean:                        { name: 'Symbol Boolean',       label: '$(symbol-boolean)',                          description: 'symbol-boolean' },
	symbolClass:                          { name: 'Symbol Class',         label: '$(symbol-class)',                            description: 'symbol-class' },
	symbolColor:                          { name: 'Symbol Color',         label: '$(symbol-color)',                            description: 'symbol-color' },
	symbolConstant:                       { name: 'Symbol Constant',      label: '$(symbol-constant)',                         description: 'symbol-constant' },
	symbolConstructor:                    { name: 'Symbol Constructor',   label: '$(symbol-constructor)',                      description: 'symbol-constructor' },
	symbolEnum:                           { name: 'Symbol Enum',          label: '$(symbol-enum)',                             description: 'symbol-enum' },
	symbolEnumMember:                     { name: 'Symbol Enum Menber',   label: '$(symbol-enum-member)',                      description: 'symbol-enum-member' },
	symbolEvent:                          { name: 'Symbol Event',         label: '$(symbol-event)',                            description: 'symbol-event' },
	symbolField:                          { name: 'Symbol Field',         label: '$(symbol-field)',                            description: 'symbol-field' },
	symbolFile:                           { name: 'Symbol File',          label: '$(symbol-file)',                             description: 'symbol-file' },
	symbolFolder:                         { name: 'Symbol Folder',        label: '$(symbol-folder)',                           description: 'symbol-folder' },
	symbolFunction:                       { name: 'Symbol Function',      label: '$(symbol-function)',                         description: 'symbol-function' },
	symbolInterface:                      { name: 'Symbol Interface',     label: '$(symbol-interface)',                        description: 'symbol-interface' },
	symbolKey:                            { name: 'Symbol Key',           label: '$(symbol-key)',                              description: 'symbol-key' },
	symbolKeyword:                        { name: 'Symbol Keyword',       label: '$(symbol-keyword)',                          description: 'symbol-keyword' },
	symbolMethod:                         { name: 'Symbol Method',        label: '$(symbol-method)',                           description: 'symbol-method' },
	symbolMisc:                           { name: 'Symbol Misc',          label: '$(symbol-misc)',                             description: 'symbol-misc' },
	symbolModule:                         { name: 'Symbol Module',        label: '$(symbol-module)',                           description: 'symbol-module' },
	symbolNamespace:                      { name: 'Symbol Namespace',     label: '$(symbol-namespace)',                        description: 'symbol-namespace' },
	symbolNull:                           { name: 'Symbol Null',          label: '$(symbol-null)',                             description: 'symbol-null' },
	symbolNumber:                         { name: 'Symbol Number',        label: '$(symbol-number)',                           description: 'symbol-number' },
	symbolNumeric:                        { name: 'Symbol Numeric',       label: '$(symbol-numeric)',                          description: 'symbol-numeric' },
	symbolObject:                         { name: 'Symbol Object',        label: '$(symbol-object)',                           description: 'symbol-object' },
	symbolOperator:                       { name: 'Symbol Operator',      label: '$(symbol-operator)',                         description: 'symbol-operator' },
	symbolPackage:                        { name: 'Symbol Package',       label: '$(symbol-package)',                          description: 'symbol-package' },
	symbolParameter:                      { name: 'Symbol Parameter',     label: '$(symbol-parameter)',                        description: 'symbol-parameter' },
	symbolProperty:                       { name: 'Symbol Property',      label: '$(symbol-property)',                         description: 'symbol-property' },
	symbolReference:                      { name: 'Symbol Reference',     label: '$(symbol-reference)',                        description: 'symbol-referenece' },
	symbolRuler:                          { name: 'Symbol Ruler',         label: '$(symbol-ruler)',                            description: 'symbol-ruler' },
	symbolSnippet:                        { name: 'Symbol Snippet',       label: '$(symbol-snippet)',                          description: 'symbol-snippet' },
	symbolString:                         { name: 'Symbol String',        label: '$(symbol-string)',                           description: 'symbol-string' },
	symbolStruct:                         { name: 'Symbol Struct',        label: '$(symbol-struct)',                           description: 'symbol-struct' },
	symbolStructure:                      { name: 'Symbol Structure',     label: '$(symbol-structure)',                        description: 'symbol-structure' },
	symbolText:                           { name: 'Symbol Text',          label: '$(symbol-text)',                             description: 'symbol-text' },
	symbolTypeParameter:                  { name: 'Symbol Type Prameter', label: '$(symbol-type-parameter)',                   description: 'symbol-type-parameter' },
	symbolUnit:                           { name: 'Symbol Unit',          label: '$(symbol-unit)',                             description: 'symbol-unit' },
	symbolValue:                          { name: 'Symbol Value',         label: '$(symbol-value)',                            description: 'symbol-value' },
	symbolVariable:                       { name: 'Symbol Variable',      label: '$(symbol-variable)',                         description: 'symbol-variable' },
	sync:                                 { name: 'Sync',                 label: '$(sync)',                                    description: 'sync' },
	syncIgnored:                          { name: 'Sync Ignored',         label: '$(sync-ignored)',                            description: 'sync-ignored' },
	tag:                                  { name: 'Tag',                  label: '$(tag)',                                     description: 'tag' },
	tagAdd:                               { name: 'Tag Add',              label: '$(tag-add)',                                 description: 'tag-add' },
	tagRemove:                            { name: 'Tag Remove',           label: '$(tag-remove)',                              description: 'tag-remove' },
	target:                               { name: 'Target',               label: '$(target)',                                  description: 'target'},
	tasklist:                             { name: 'Tasklist',             label: '$(tasklist)',                                description: 'tasklist' },
	telescope:                            { name: 'Telescope',            label: '$(telescope)',                               description: 'telescope' },
	terminalBash:                         { name: 'Terminal Bash',        label: '$(terminal-bash)',                           description: 'terminal-bash' },
	terminalCmd:                          { name: 'Terminal Cmd',         label: '$(terminal-cmd)',                            description: 'terminal-cmd' },
	terminalDebian:                       { name: 'Terminal Debian',      label: '$(terminal-debian)',                         description: 'terminal-debian' },
	terminalLinux:                        { name: 'Terminal Linux',       label: '$(terminal-linux)',                          description: 'terminal-linux' },
	terminalPowershell:                   { name: 'Terminal Powershell',  label: '$(terminal-powershell)',                     description: 'terminal-powershell' },
	terminalTmux:                         { name: 'Terminal Tmux',        label: '$(terminal-tmux)',                           description: 'terminal-tmux' },
	terminalUbuntu:                       { name: 'Terminal Ubuntu',      label: '$(terminal-ubuntu)',                         description: 'terminal-ubuntu' },
	terminal:                             { name: 'Terminal',             label: '$(terminal)',                                description: 'terminal' },
	textSize:                             { name: 'Text Size',            label: '$(text-size)',                               description: 'text-size' },
	threeBars:                            { name: 'Three Bars',           label: '$(three-bars)',                              description: 'three-bars' },
	thumbsdown:                           { name: 'Thumbsdown',           label: '$(thumbsdown)',                              description: 'thumbsdown' },
	thumbsup:                             { name: 'Thumbsup',             label: '$(thumbsup)',                                description: 'thumbsup' },
	tools:                                { name: 'Tools',                label: '$(tools)',                                   description: 'tools' },
	trashcan:                             { name: 'Trashcan',             label: '$(trashcan)',                                description: 'trashcan' },
	triangleDown:                         { name: 'Triangle Down',        label: '$(triangle-down)',                           description: 'triangle-down' },
	triangleLeft:                         { name: 'Triangle Left',        label: '$(triangle-left)',                           description: 'triangle-left' },
	triangleRight:                        { name: 'Triangle Right',       label: '$(triangle-right)',                          description: 'triangle-right' },
	triangleUp:                           { name: 'Triangle Up',          label: '$(triangle-up)',                             description: 'triangle-up' },
	twitter:                              { name: 'Twitter',              label: '$(twitter)',                                 description: 'twitter' },
	typeHierarchy:                        { name: 'Type Hierarchy',       label: '$(type-hierarchy)',                          description: 'type-hierarchy' },
	typeHierarchySub:                     { name: 'Type Hierarchy Sub',   label: '$(type-hierarchy-sub)',                      description: 'type-hierarchy-sub' },
	typeHierarchySuper:                   { name: 'Type Hierarchy Super', label: '$(type-hierarchy-super)',                    description: 'type-hierarchy-super' },
};
