export const icons = {
	unfold:                               { name: 'Unfold',              label: '$(unfold)',                                  description: 'unfold' },
	ungroupByRefType:                     { name: 'Ungroup By Ref Type', label: '$(ungroup-by-ref-type)',                     description: 'ungroup-by-ref-type' },
	unlock:                               { name: 'Unlock',              label: '$(unlock)',                                  description: 'unlock' },
	unmute:                               { name: 'Unmute',              label: '$(unmute)',                                  description: 'unmute' },
	unverified:                           { name: 'Unverified',          label: '$(unverified)',                              description: 'unverified' },
	variable:                             { name: 'Variable',            label: '$(variable)',                                description: 'variable' },
	verified:                             { name: 'Verfied',             label: '$(verified)',                                description: 'verified' },
	versions:                             { name: 'Versions',            label: '$(versions)',                                description: 'versions' },
	vm:                                   { name: 'VM',                  label: '$(vm)',                                      description: 'vm' },
	vmActive:                             { name: 'VM Active',           label: '$(vm-active)',                               description: 'vm-active' },
	vmConnect:                            { name: 'VM Connect',          label: '$(vm-connect)',                              description: 'vm-connect' },
	vmOutline:                            { name: 'VM Outline',          label: '$(vm-outline)',                              description: 'vm-outline' },
	vmRunning:                            { name: 'VM Running',          label: '$(vm-running)',                              description: 'vm-running' },
	warning:                              { name: 'Warning',             label: '$(warning)',                                 description: 'warning' },
	watch:                                { name: 'Watch',               label: '$(watch)',                                   description: 'watch' },
	whitespace:                           { name: 'Whitespace',          label: '$(whitespace)',                              description: 'whitespace' },
	wholeWord:                            { name: 'Wholeword',           label: '$(whole-word)',                              description: 'whole-word' },
	window:                               { name: 'Window',              label: '$(window)',                                  description: 'window' },
	wordWrap:                             { name: 'Word Wrap',           label: '$(word-wrap)',                               description: 'word-wrap' },
	wrench:                               { name: 'Wrench',              label: '$(wrench)',                                  description: 'wrench' },
	wrenchSubaction:                      { name: 'Wrench Subaction',    label: '$(wrench-subaction)',                        description: 'wrench-subaction' },
	x:                                    { name: 'X',                   label: '$(x)',                                       description: 'x' },
	zap:                                  { name: 'Zap',                 label: '$(zap)',                                     description: 'zap' },
	zoomIn:                               { name: 'Zoom In',             label: '$(zoom-in)',                                 description: 'zoom-in' },
	zoomOut:                              { name: 'Zoom Out',            label: '$(zoom-out)',                                description: 'zoom-out' },
};
